version: '3.8'

services:
  knowledge-system:
    build:
      context: ./knowledge_system
    image: localhost/linux-agent-knowledge-system:local
    ports:
      - "8085:8085"
    networks:
      - agent-network

  agent-system:
    build:
      context: ./agent_system
    image: localhost/linux-agent-agent-system:local
    ports:
      - "8082:8082"
    networks:
      - agent-network
    environment:
      - KNOWLEDGE_SYSTEM_URL=http://knowledge-system:8085
    depends_on:
      - knowledge-system

networks:
  agent-network:
    driver: bridge
