version: '3.8'

services:
  agent-system:
    build: ./agent-system
    ports:
      - "8082:8082"
    environment:
      - KNOWLEDGE_SYSTEM_URL=http://knowledge-system:8084
      - COMMAND_EXECUTOR_URL=http://command-executor:8085
      - DRY_RUN=false
      - DIRECT_EXECUTION=true
      - DATA_DIR=/app/data
      - DEBUG_LEVEL=DEBUG
      - VERBOSE_LEVEL=3
      - COLOR_OUTPUT=true
      - COMMAND_TIMEOUT=60
      - OLLAMA_HOST=100.100.100.160
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=ALIENTELLIGENCE/linuxcmdxpert
    volumes:
      - agent_data:/app/data
      - ./frontend:/app/frontend:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  knowledge-system:
    build: ./knowledge-system
    ports:
      - "8084:8084"
    environment:
      - DATA_DIR=/app/data
    volumes:
      - knowledge_data:/app/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Mock service for the command executor
  command-executor:
    image: alpine:latest
    command: sh -c "apk add --no-cache python3 && python3 -m http.server 8085"
    ports:
      - "8085:8085"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8085/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  agent_data:
  knowledge_data:
