version: '3.8'

services:
  agent-system:
    build: ./agent-system
    ports:
      - "8082:8082"
    environment:
      - KNOWLEDGE_SYSTEM_URL=http://knowledge-system:8084
      - DRY_RUN=true
      - DEBUG_LEVEL=DEBUG
    volumes:
      - agent_data:/app/data
    restart: unless-stopped

  knowledge-system:
    build: ./knowledge-system
    ports:
      - "8084:8084"
    environment:
      - DATA_DIR=/app/data
    volumes:
      - knowledge_data:/app/data
    restart: unless-stopped

volumes:
  agent_data:
  knowledge_data:
