version: '3.8'

services:
  api-gateway:
    build: 
      no-cache: true
      image: localhost/agent_ 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8081
    volumes:
      - api_data:/app/data
    depends_on:
      - orchestrator
    restart: unless-stopped

  orchestrator:
    build: 
      no-cache: true
      image: localhost/agent_ 
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - AGENT_SYSTEM_URL=http://agent-system:8082
      - VM_MANAGER_URL=http://vm-manager:8083
    volumes:
      - orchestrator_data:/app/data
    depends_on:
      - agent-system
      - vm-manager
    restart: unless-stopped

  agent-system:
    build: 
      no-cache: true
      image: localhost/agent_ ./agent-system
    ports:
      - "8082:8082"
    environment:
      - KNOWLEDGE_SYSTEM_URL=http://knowledge-system:8084
      - COMMAND_EXECUTOR_URL=http://command-executor:8085
      - VM_MANAGER_URL=http://vm-manager:8083
      - DRY_RUN=true
      - DEBUG_LEVEL=DEBUG
    volumes:
      - agent_data:/app/data
    depends_on:
      - knowledge-system
      - command-executor
    restart: unless-stopped

  vm-manager:
    build: 
      no-cache: true
      image: localhost/agent_ 
      context: ./vm-manager
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - VM_MANAGER_PORT=8083
      - LIBVIRT_URI=qemu:///system
      - VM_DATA_DIR=/var/lib/linux-agent-system/vms
      - VM_TEMPLATE_PATH=/var/lib/libvirt/images/opensuse-tumbleweed-template.qcow2
      - ENABLE_SIMULATION=true
    volumes:
      - vm_data:/var/lib/linux-agent-system/vms
      - /var/lib/linux-agent-system:/var/lib/linux-agent-system
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - /var/lib/libvirt/images:/var/lib/libvirt/images
     privileged: true
    restart: unless-stopped

  command-executor:
    build: 
      no-cache: true
      image: localhost/agent_ 
      context: ./command-executor
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - COMMAND_EXECUTOR_PORT=8085
      - VM_MANAGER_URL=http://vm-manager:8083
    volumes:
      - executor_data:/app/data
    restart: unless-stopped

  knowledge-system:
    build: 
      no-cache: true
      image: localhost/agent_ ./knowledge-system
    ports:
      - "8084:8084"
    environment:
      - DATA_DIR=/app/data
    volumes:
      - knowledge_data:/app/data
    restart: unless-stopped

volumes:
  api_data:
  orchestrator_data:
  agent_data:
  vm_data:
  executor_data:
  knowledge_data:
