version: '3.8'

services:
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    image: glinux-agent-api-gateway:local
    ports:
      - "8080:8080"
    volumes:
      - ./api_gateway:/app
    depends_on:
      - orchestrator
    networks:
      - agent-network
    environment:
      - ORCHESTRATOR_URL=http://orchestrator:8081

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    image: glinux-agent-orchestrator:local  
    ports:
      - "8081:8081"
    volumes:
      - ./orchestrator:/app
    depends_on:
      - agent-system
      - vm-manager
      - command-executor
    networks:
      - agent-network
    environment:
      - AGENT_SYSTEM_URL=http://agent-system:8082
      - VM_MANAGER_URL=http://vm-manager:8083
      - COMMAND_EXECUTOR_URL=http://command-executor:8084

  agent-system:
    build:
      context: ./agent_system
      dockerfile: Dockerfile
    image: glinux-agent-agent-system:local
    ports:
      - "8082:8082"
    volumes:
      - ./agent_system:/app:Z
    depends_on:
      - knowledge-system
    networks:
      - agent-network
    environment:
      - KNOWLEDGE_SYSTEM_URL=http://knowledge-system:8085

  vm-manager:
    build:
      context: ./vm_manager
      dockerfile: Dockerfile
    image: glinux-agent-vm-manager:local
    ports:
      - "8083:8083"
    volumes:
      - ./vm_manager:/app
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
    privileged: true
    networks:
      - agent-network
    environment:
      - LIBVIRT_CONNECTION=qemu:///system

  command-executor:
    build:
      context: ./command_executor
      dockerfile: Dockerfile
    image: glinux-agent-command-executor:local
    ports:
      - "8084:8084"
    volumes:
      - ./command_executor:/app
    networks:
      - agent-network

  knowledge-system:
    build:
      context: ./knowledge_system
      dockerfile: Dockerfile
    image: glinux-agent-knowledge-system:local
    ports:
      - "8085:8085"
    volumes:
      - ./knowledge_system:/app:Z
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
